const ActionTypes = {
  UPDATE_LOADING: "UPDATE_LOADING",
  GET_ITEMS: "GET_ITEMS",
  GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILURE: "GET_ITEMS_FAILURE",
  CLEAR_ITEMS_LIST: "CLEAR_ITEMS_LIST",
  ADD_LIKE: "ADD_LIKE",
  REMOVE_LIKE: "REMOVE_LIKE",
  ADD_DISLIKE: "ADD_DISLIKE",
  REMOVE_DISLIKE: "REMOVE_DISLIKE",
  ADD_BOOKMARK: "ADD_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK"
};

export default ActionTypes;
